// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Patient struct {
	ID        uuid.UUID
	Name      string
	Age       int32
	Gender    string
	Address   sql.NullString
	Diagnosis sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Staff struct {
	ID        uuid.UUID
	Name      string
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
	PwHash    string
}
