root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "env"]
exclude_dir = ["tmp", "vendor"]
stop_on_error = true
log = "build-errors.log"

[run]
cmd = "./tmp/main"

[watch]
paths = [
    ".",
    "internal",
    "configs",
    "db/migrations",
]

[log]
time = true
main_only = false

[misc]
clean_on_exit = true

[screen]
clear = true
